- name: Playbook for staging env
  hosts: staging
  vars:
    env: staging
    remote_role: app
  become: yes
  vars_files:
    - vars/common.yml
    - vars/staging.yml
  roles:
    - env
    - git
    - vim
    - ruby
    - nginx
    - mysql
    - unicorn
